---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: urlshortener-role
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - urlshortener.av0.de
  resources:
  - redirects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - urlshortener.av0.de
  resources:
  - redirects/finalizers
  verbs:
  - update
- apiGroups:
  - urlshortener.av0.de
  resources:
  - redirects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - urlshortener.av0.de
  resources:
  - shortlinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - urlshortener.av0.de
  resources:
  - shortlinks/finalizers
  verbs:
  - update
- apiGroups:
  - urlshortener.av0.de
  resources:
  - shortlinks/status
  verbs:
  - get
  - patch
  - update
