apiVersion: urlshortener.av0.de/v1alpha1
kind: ShortLink
metadata:
  name: cedi
spec:
  target: "https://cedi.dev"
  after: 99
---
apiVersion: urlshortener.av0.de/v1alpha1
kind: ShortLink
metadata:
  name: swag
spec:
  target: "https://short.av0.de/swagger/index.html#/"
  code: 308
