apiVersion: urlshortener.cedi.dev/v1alpha1
kind: ShortLink
metadata:
  name: cedi
spec:
  target: "https://cedi.dev"
  after: 99
---
apiVersion: urlshortener.cedi.dev/v1alpha1
kind: ShortLink
metadata:
  name: swag
spec:
  target: "https://short.cedi.dev/swagger/index.html#/"
  code: 308
